// 역대 대선 1·2위(+주목할 제3) 후보의 한글/영문 표기와 초상화.
// 선거인단·전국 득표율 등 수치는 백엔드 실데이터(/president/national)에서 가져오고,
// 여기서는 DB 의 혼재된 후보명(예: "CLINTON, HILLARY")을 깔끔한 표기로 덮어쓰는 역할만 한다.
// 초상화는 Wikimedia Commons 안정 URL(Special:FilePath). 파일명은 실제 존재를 확인했다.

// en.wikipedia 의 Special:FilePath 는 Commons·로컬 파일 모두 해석한다(역대 인물 포함).
const FILE = (name) =>
  `https://en.wikipedia.org/wiki/Special:FilePath/${encodeURIComponent(name)}?width=240`;

export const portraitUrl = FILE;

// 인물 카드(연도 간 재사용). 부시·클린턴은 동명이인이라 키를 분리.
const P = {
  carter:   { ko: "지미 카터",      en: "Jimmy Carter",       img: "Jimmy_Carter.jpg" },
  ford:     { ko: "제럴드 포드",     en: "Gerald Ford",        img: "Gerald_Ford_presidential_portrait_(cropped).jpg" },
  reagan:   { ko: "로널드 레이건",   en: "Ronald Reagan",      img: "Official_Portrait_of_President_Reagan_1981.jpg" },
  mondale:  { ko: "월터 먼데일",     en: "Walter Mondale",     img: "Walter_Mondale_1977_vice_presidential_portrait.jpg" },
  bush41:   { ko: "조지 H. W. 부시", en: "George H. W. Bush",  img: "George_H._W._Bush_presidential_portrait_(cropped).jpg" },
  dukakis:  { ko: "마이클 듀카키스", en: "Michael Dukakis",    img: "Michael_Dukakis.jpg" },
  clinton:  { ko: "빌 클린턴",       en: "Bill Clinton",       img: "Bill_Clinton.jpg" },
  dole:     { ko: "밥 돌",          en: "Bob Dole",           img: "Bob_Dole,_PCCWW_photo_portrait.JPG" },
  bush43:   { ko: "조지 W. 부시",    en: "George W. Bush",     img: "George-W-Bush.jpeg" },
  gore:     { ko: "앨 고어",         en: "Al Gore",            img: "Al_Gore,_Vice_President_of_the_United_States,_official_portrait_1994.jpg" },
  kerry:    { ko: "존 케리",         en: "John Kerry",         img: "John_Kerry_official_Secretary_of_State_portrait.jpg" },
  obama:    { ko: "버락 오바마",     en: "Barack Obama",       img: "President_Barack_Obama.jpg" },
  mccain:   { ko: "존 매케인",       en: "John McCain",        img: "John_McCain_official_portrait_2009.jpg" },
  romney:   { ko: "밋 롬니",         en: "Mitt Romney",        img: "Mitt_Romney_by_Gage_Skidmore_6_cropped.jpg" },
  trump:    { ko: "도널드 트럼프",   en: "Donald Trump",       img: "Donald_Trump_official_portrait.jpg" },
  hclinton: { ko: "힐러리 클린턴",   en: "Hillary Clinton",    img: "Hillary_Clinton_official_Secretary_of_State_portrait_crop.jpg" },
  biden:    { ko: "조 바이든",       en: "Joe Biden",          img: "Joe_Biden_presidential_portrait.jpg" },
  harris:   { ko: "카멀라 해리스",   en: "Kamala Harris",      img: "Kamala_Harris_Vice_Presidential_Portrait.jpg" },
};

// 연도별 정당 대표 후보(DEM/REP) + 주목할 제3후보(있을 때).
export const POTUS = {
  1976: { DEM: P.carter,   REP: P.ford },
  1980: { DEM: P.carter,   REP: P.reagan,  third: { ko: "존 B. 앤더슨", en: "John B. Anderson", party: "무소속" } },
  1984: { DEM: P.mondale,  REP: P.reagan },
  1988: { DEM: P.dukakis,  REP: P.bush41 },
  1992: { DEM: P.clinton,  REP: P.bush41,  third: { ko: "로스 페로",   en: "Ross Perot",       party: "무소속" } },
  1996: { DEM: P.clinton,  REP: P.dole,    third: { ko: "로스 페로",   en: "Ross Perot",       party: "개혁당" } },
  2000: { DEM: P.gore,     REP: P.bush43 },
  2004: { DEM: P.kerry,    REP: P.bush43 },
  2008: { DEM: P.obama,    REP: P.mccain },
  2012: { DEM: P.obama,    REP: P.romney },
  2016: { DEM: P.hclinton, REP: P.trump },
  2020: { DEM: P.biden,    REP: P.trump },
  2024: { DEM: P.harris,   REP: P.trump },
};

// ── 역대(1789-1972) ─────────────────────────────────────────────
// 정당(시대별) → 한글·색. 카드/EC 바에서 사용(지도 색은 백엔드 HIST_PARTY 가 별도 관리).
export const PARTY_HIST = {
  IND:  { ko: "무소속·초당파", color: "#8D6E63" },
  FED:  { ko: "연방당",       color: "#C9A227" },
  DR:   { ko: "민주공화당",   color: "#3C9D6E" },
  NR:   { ko: "국민공화당",   color: "#8E6FB5" },
  DEM:  { ko: "민주당",       color: "#1565C0" },
  WHG:  { ko: "휘그당",       color: "#E08A3C" },
  REP:  { ko: "공화당",       color: "#D32F2F" },
  SD:   { ko: "남부 민주당",  color: "#5C8AE6" },
  LR:   { ko: "자유공화당",   color: "#EF9A9A" },
  PROG: { ko: "진보당",       color: "#2E9E5B" },
};

// 인물 한글/영문/초상화(Wikipedia 대표 이미지 파일명, REST API 로 추출·검증).
export const HIST_PEOPLE = {
  washington: { ko: '조지 워싱턴', en: "George Washington", img: "Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg" },
  jadams: { ko: '존 애덤스', en: "John Adams", img: "John_Adams_Portrait.jpg" },
  jefferson: { ko: '토머스 제퍼슨', en: "Thomas Jefferson", img: "Official_Presidential_portrait_of_Thomas_Jefferson_(by_Rembrandt_Peale,_1800).jpg" },
  madison: { ko: '제임스 매디슨', en: "James Madison", img: "James_Madison.jpg" },
  monroe: { ko: '제임스 먼로', en: "James Monroe", img: "James_Monroe_White_House_portrait_1819_(cropped)(2).jpg" },
  jqadams: { ko: '존 퀸시 애덤스', en: "John Quincy Adams", img: "JQA_Photo_Crop_(cropped).jpg" },
  jackson: { ko: '앤드루 잭슨', en: "Andrew Jackson", img: "Andrew_jackson_head_(cropped).jpg" },
  vanburen: { ko: '마틴 밴 뷰런', en: "Martin Van Buren", img: "Martin_Van_Buren_by_Mathew_Brady_c1855-58-(4).jpg" },
  whharrison: { ko: '윌리엄 헨리 해리슨', en: "William Henry Harrison", img: "William_Henry_Harrison_crop.jpg" },
  polk: { ko: '제임스 K. 포크', en: "James K. Polk", img: "Polk_crop.jpg" },
  taylor: { ko: '재커리 테일러', en: "Zachary Taylor", img: "Zachary_Taylor_restored_and_cropped_(3.5x4.5_cropped)_(2).jpg" },
  pierce: { ko: '프랭클린 피어스', en: "Franklin Pierce", img: "Mathew_Brady_-_Franklin_Pierce_-_alternate_crop_(cropped)(2).jpg" },
  buchanan: { ko: '제임스 뷰캐넌', en: "James Buchanan", img: "James_Buchanan.jpg" },
  lincoln: { ko: '에이브러햄 링컨', en: "Abraham Lincoln", img: "Abraham_Lincoln_1863_Portrait_(3x4_cropped).jpg" },
  grant: { ko: '율리시스 S. 그랜트', en: "Ulysses S. Grant", img: "Ulysses_S._Grant_1870-1880_(cropped).jpg" },
  hayes: { ko: '러더퍼드 헤이스', en: "Rutherford B. Hayes", img: "President_Rutherford_Hayes_1870_-_1880_Restored.jpg" },
  garfield: { ko: '제임스 가필드', en: "James A. Garfield", img: "James_Abram_Garfield,_photo_portrait_seated.jpg" },
  cleveland: { ko: '그로버 클리블랜드', en: "Grover Cleveland", img: "StephenGroverCleveland.jpg" },
  bharrison: { ko: '벤저민 해리슨', en: "Benjamin Harrison", img: "Pach_Brothers_-_Benjamin_Harrison_(cropped)_(cropped).jpg" },
  mckinley: { ko: '윌리엄 매킨리', en: "William McKinley", img: "McKinley_(cropped).jpg" },
  troosevelt: { ko: '시어도어 루스벨트', en: "Theodore Roosevelt", img: "Theodore_Roosevelt_by_the_Pach_Bros_(4x5_cropped).jpg" },
  taft: { ko: '윌리엄 H. 태프트', en: "William Howard Taft", img: "William_Howard_Taft_by_Pach_Brothers_(3x4_ropped)_(cropped).jpg" },
  wilson: { ko: '우드로 윌슨', en: "Woodrow Wilson", img: "President_Woodrow_Wilson_Harris_&_Ewing_(3x4_cropped_b).jpg" },
  harding: { ko: '워런 하딩', en: "Warren G. Harding", img: "Warren_G._Harding_1920s_portrait_(3x4_cropped)_(cropped).jpg" },
  coolidge: { ko: '캘빈 쿨리지', en: "Calvin Coolidge", img: "President_Calvin_Coolidge,_1924_portrait_photograph_(3x4_cropped_2).jpeg" },
  hoover: { ko: '허버트 후버', en: "Herbert Hoover", img: "President_Hoover_portrait.jpg" },
  fdr: { ko: '프랭클린 D. 루스벨트', en: "Franklin D. Roosevelt", img: "FDR-1944-Campaign-Portrait_(3x4_retouched,_cropped).jpg" },
  truman: { ko: '해리 S. 트루먼', en: "Harry S. Truman", img: "TRUMAN_58-766-06_(cropped).jpg" },
  eisenhower: { ko: '드와이트 D. 아이젠하워', en: "Dwight D. Eisenhower", img: "Dwight_D._Eisenhower,_official_photo_portrait,_May_29,_1959_(cropped)(3).jpg" },
  kennedy: { ko: '존 F. 케네디', en: "John F. Kennedy", img: "John_F._Kennedy,_White_House_color_photo_portrait.jpg" },
  lbj: { ko: '린든 B. 존슨', en: "Lyndon B. Johnson", img: "Lyndon_B._Johnson,_photo_portrait,_color_(3x4_cropped)(3).jpg" },
  nixon: { ko: '리처드 닉슨', en: "Richard Nixon", img: "Richard_Nixon_presidential_portrait_(1).jpg" },
  burr: { ko: '에런 버', en: "Aaron Burr", img: "John_Vanderlyn_-_Official_Portrait_of_Vice_President_Aaron_Burr.jpg" },
  cpinckney: { ko: '찰스 핑크니', en: "Charles C. Pinckney", img: "James_Earl_-_General_Charles_Cotesworth_Pinckney_-_Google_Art_Project.jpg" },
  dclinton: { ko: '디윗 클린턴', en: "DeWitt Clinton", img: "DeWitt_Clinton_by_Rembrandt_Peale.jpg" },
  king: { ko: '루퍼스 킹', en: "Rufus King", img: "Gilbert_Stuart_-_Portrait_of_Rufus_King_(1819-1820)_-_Google_Art_Project.jpg" },
  clay: { ko: '헨리 클레이', en: "Henry Clay", img: "Clay_1848.jpg" },
  cass: { ko: '루이스 캐스', en: "Lewis Cass", img: "Lewis_Cass_circa_1855.jpg" },
  scott: { ko: '윈필드 스콧', en: "Winfield Scott", img: "Winfield_Scott_by_Fredricks,_1862_crop.jpg" },
  fremont: { ko: '존 C. 프리몬트', en: "John C. Frémont", img: "John_Charles_Fremont_Oval.png" },
  breckinridge: { ko: '존 C. 브레킨리지', en: "John C. Breckinridge", img: "John_C._Breckinridge_1860_portrait_(3x4_cropped).jpg" },
  mcclellan: { ko: '조지 매클렐런', en: "George B. McClellan", img: "George_B_McClellan_-_retouched,_cropped.jpg" },
  seymour: { ko: '호레이쇼 시모어', en: "Horatio Seymour", img: "Horatio_Seymour_(cropped,_retouched).jpg" },
  greeley: { ko: '호러스 그릴리', en: "Horace Greeley", img: "Horace_Greeley_restored.jpg" },
  tilden: { ko: '새뮤얼 틸던', en: "Samuel J. Tilden", img: "Samuel_Tilden._Portrait_of_the_American_politician,_who_served_as_the_25th_Governor_of_New_York,_Samuel_Jones_Tilden_(1814-1886),_by_José_María_Mora,_c._1870.jpg" },
  hancock: { ko: '윈필드 S. 핸콕', en: "Winfield S. Hancock", img: "Gen._Winfield_S._Hancock_-_NARA_-_529369_(cropped,_retouched).jpg" },
  blaine: { ko: '제임스 블레인', en: "James G. Blaine", img: "James_G._Blaine_-_Brady-Handy_(cropped).jpg" },
  bryan: { ko: '윌리엄 J. 브라이언', en: "William J. Bryan", img: "Portrait_of_Secretary_William_Jennings_Bryan_of_Nebraska,_1913.jpeg" },
  parker: { ko: '올턴 파커', en: "Alton B. Parker", img: "Alton_Brooks_Parker_Portrait_(3x4_cropped).jpg" },
  hughes: { ko: '찰스 에번스 휴스', en: "Charles E. Hughes", img: "Charles_Evans_Hughes_cph.3b15401.jpg" },
  cox: { ko: '제임스 M. 콕스', en: "James M. Cox", img: "James_M._Cox_Portrait_(3x4_cropped_b).jpg" },
  davis: { ko: '존 W. 데이비스', en: "John W. Davis", img: "DAVIS,_JOHN_W._HONORABLE_LCCN2016862563_(cropped).jpg" },
  smith: { ko: '앨 스미스', en: "Al Smith", img: "SMITH,_ALFRED._HONORABLE_LCCN2016862532_Trim.jpg" },
  landon: { ko: '알프 랜던', en: "Alf Landon", img: "Unsuccessful_1936.jpg" },
  willkie: { ko: '웬델 윌키', en: "Wendell Willkie", img: "Portrait_of_Wendell_Lewis_Willkie_Sitting_by_Wall_(cropped).jpg" },
  dewey: { ko: '토머스 듀이', en: "Thomas E. Dewey", img: "Thomas_Dewey_in_1944.jpg" },
  stevenson: { ko: '애들레이 스티븐슨', en: "Adlai Stevenson II", img: "Portrait_of_Ambassador_Adlai_E._Stevenson_II_(cropped).jpg" },
  goldwater: { ko: '배리 골드워터', en: "Barry Goldwater", img: "Senator_Goldwater_1960.jpg" },
  humphrey: { ko: '휴버트 험프리', en: "Hubert Humphrey", img: "Hubert_Humphrey_vice_presidential_portrait.jpg" },
  mcgovern: { ko: '조지 맥거번', en: "George McGovern", img: "George_McGovern_(D-SD).jpg" },
};

// 연도별 [당선, 차점] = [인물키, 정당키, 선거인단]. 첫 원소가 당선자.
// ev/total 은 권위 사료(선거인단 실제 배분). note 는 맥락(접전·하원결선·다당제 등).
export const POTUS_HIST = {
  1789: { ev: 69,  c: [["washington", "IND", 69], ["jadams", "IND", 34]], note: "선거인단 만장일치 — 정당 형성 이전" },
  1792: { ev: 132, c: [["washington", "IND", 132], ["jadams", "FED", 77]], note: "만장일치 재선" },
  1796: { ev: 138, c: [["jadams", "FED", 71], ["jefferson", "DR", 68]] },
  1800: { ev: 138, c: [["jefferson", "DR", 73], ["burr", "DR", 73]], note: "버와 동수(73) → 하원 결선으로 제퍼슨 당선" },
  1804: { ev: 176, c: [["jefferson", "DR", 162], ["cpinckney", "FED", 14]] },
  1808: { ev: 175, c: [["madison", "DR", 122], ["cpinckney", "FED", 47]] },
  1812: { ev: 217, c: [["madison", "DR", 128], ["dclinton", "FED", 89]] },
  1816: { ev: 217, c: [["monroe", "DR", 183], ["king", "FED", 34]] },
  1820: { ev: 232, c: [["monroe", "DR", 231], ["jqadams", "DR", 1]], note: "사실상 무경쟁('호감의 시대')" },
  1824: { ev: 261, c: [["jqadams", "NR", 84], ["jackson", "DEM", 99]], note: "잭슨이 선거인단 최다(99)였으나 과반 미달 → 하원이 애덤스 선출" },
  1828: { ev: 261, c: [["jackson", "DEM", 178], ["jqadams", "NR", 83]] },
  1832: { ev: 286, c: [["jackson", "DEM", 219], ["clay", "NR", 49]] },
  1836: { ev: 294, c: [["vanburen", "DEM", 170], ["whharrison", "WHG", 73]], note: "휘그당이 지역별 복수 후보로 분산 출마" },
  1840: { ev: 294, c: [["whharrison", "WHG", 234], ["vanburen", "DEM", 60]] },
  1844: { ev: 275, c: [["polk", "DEM", 170], ["clay", "WHG", 105]] },
  1848: { ev: 290, c: [["taylor", "WHG", 163], ["cass", "DEM", 127]] },
  1852: { ev: 296, c: [["pierce", "DEM", 254], ["scott", "WHG", 42]] },
  1856: { ev: 296, c: [["buchanan", "DEM", 174], ["fremont", "REP", 114]], note: "공화당 첫 대선 출마(프리몬트)" },
  1860: { ev: 303, c: [["lincoln", "REP", 180], ["breckinridge", "SD", 72]], note: "4파전 — 더글러스(민주) 12·벨(입헌통일) 39" },
  1864: { ev: 233, c: [["lincoln", "REP", 212], ["mcclellan", "DEM", 21]], note: "남부 연합주 미참여(남북전쟁)" },
  1868: { ev: 294, c: [["grant", "REP", 214], ["seymour", "DEM", 80]] },
  1872: { ev: 352, c: [["grant", "REP", 286], ["greeley", "LR", 66]], note: "그릴리 선거 직후 사망 → 선거인단 분산" },
  1876: { ev: 369, c: [["hayes", "REP", 185], ["tilden", "DEM", 184]], note: "1표 차 — 선거위원회가 분쟁주 판정" },
  1880: { ev: 369, c: [["garfield", "REP", 214], ["hancock", "DEM", 155]] },
  1884: { ev: 401, c: [["cleveland", "DEM", 219], ["blaine", "REP", 182]] },
  1888: { ev: 401, c: [["bharrison", "REP", 233], ["cleveland", "DEM", 168]], note: "클리블랜드가 전국 득표는 앞섰으나 선거인단 패배" },
  1892: { ev: 444, c: [["cleveland", "DEM", 277], ["bharrison", "REP", 145]], note: "유일한 비연속 재선" },
  1896: { ev: 447, c: [["mckinley", "REP", 271], ["bryan", "DEM", 176]] },
  1900: { ev: 447, c: [["mckinley", "REP", 292], ["bryan", "DEM", 155]] },
  1904: { ev: 476, c: [["troosevelt", "REP", 336], ["parker", "DEM", 140]] },
  1908: { ev: 483, c: [["taft", "REP", 321], ["bryan", "DEM", 162]] },
  1912: { ev: 531, c: [["wilson", "DEM", 435], ["troosevelt", "PROG", 88]], note: "공화 분열 — 태프트(공화) 8" },
  1916: { ev: 531, c: [["wilson", "DEM", 277], ["hughes", "REP", 254]] },
  1920: { ev: 531, c: [["harding", "REP", 404], ["cox", "DEM", 127]] },
  1924: { ev: 531, c: [["coolidge", "REP", 382], ["davis", "DEM", 136]], note: "라폴레트(진보) 13" },
  1928: { ev: 531, c: [["hoover", "REP", 444], ["smith", "DEM", 87]] },
  1932: { ev: 531, c: [["fdr", "DEM", 472], ["hoover", "REP", 59]], note: "대공황 — 뉴딜 연합 형성" },
  1936: { ev: 531, c: [["fdr", "DEM", 523], ["landon", "REP", 8]], note: "역대 최대 선거인단 압승" },
  1940: { ev: 531, c: [["fdr", "DEM", 449], ["willkie", "REP", 82]] },
  1944: { ev: 531, c: [["fdr", "DEM", 432], ["dewey", "REP", 99]] },
  1948: { ev: 531, c: [["truman", "DEM", 303], ["dewey", "REP", 189]], note: "여론조사 뒤집은 트루먼 — 서몬드(주권민주) 39" },
  1952: { ev: 531, c: [["eisenhower", "REP", 442], ["stevenson", "DEM", 89]] },
  1956: { ev: 531, c: [["eisenhower", "REP", 457], ["stevenson", "DEM", 73]] },
  1960: { ev: 537, c: [["kennedy", "DEM", 303], ["nixon", "REP", 219]] },
  1964: { ev: 538, c: [["lbj", "DEM", 486], ["goldwater", "REP", 52]] },
  1968: { ev: 538, c: [["nixon", "REP", 301], ["humphrey", "DEM", 191]], note: "월리스(미국독립) 46" },
  1972: { ev: 538, c: [["nixon", "REP", 520], ["mcgovern", "DEM", 17]] },
};
