"""state_base.py + aug_*.json 병합 → frontend/src/content/states_info.js 생성.
인구순위(popRank)·면적순위(areaRank)는 50개 주 기준으로 여기서 계산(DC 제외, null).
실행: python tools/build_states_info.py"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from state_base import BASE

ROOT = pathlib.Path(__file__).resolve().parent.parent
AUG_DIR = ROOT / "tools"
OUT = ROOT / "frontend" / "src" / "content" / "states_info.js"

# aug_*.json 병합
aug = {}
missing = []
for tag in "ABCDEFG":
    p = AUG_DIR / f"aug_{tag}.json"
    if not p.exists():
        missing.append(tag); continue
    data = json.loads(p.read_text(encoding="utf-8"))
    aug.update(data)
if missing:
    print("경고: 누락된 배치", missing)

# 기반 + 리서치 병합
rec = {}
for fips, b in BASE.items():
    a = aug.get(fips, {})
    rec[fips] = {
        "po": b["po"], "ko": b["ko"], "en": b["en"], "cap": b["cap"],
        "adm": b["adm"], "order": b["order"], "area": b["area"], "ev": b["ev"],
        "pop": a.get("pop2020"),
        "people": a.get("people", {}),
        "nationalParks": a.get("nationalParks", []),
        "stateParks": a.get("stateParks", []),
        "teams": a.get("teams", {}),
        "landmarks": a.get("landmarks", []),
    }

# 순위 계산: 50개 주(order != None)만, DC 제외
states50 = [f for f in rec if rec[f]["order"] is not None]
by_pop = sorted([f for f in states50 if rec[f]["pop"]], key=lambda f: rec[f]["pop"], reverse=True)
for i, f in enumerate(by_pop, 1):
    rec[f]["popRank"] = i
by_area = sorted(states50, key=lambda f: rec[f]["area"], reverse=True)
for i, f in enumerate(by_area, 1):
    rec[f]["areaRank"] = i
for f in rec:
    rec[f].setdefault("popRank", None)
    rec[f].setdefault("areaRank", None)

# 검증 로그
no_pop = [rec[f]["po"] for f in rec if rec[f]["pop"] is None]
no_lm = [rec[f]["po"] for f in rec if not rec[f]["landmarks"]]
print(f"주 {len(rec)}개 · 인구누락 {no_pop} · 랜드마크누락 {no_lm}")

body = json.dumps(rec, ensure_ascii=False, indent=2)
OUT.write_text(
    "// AUTO-GENERATED by tools/build_states_info.py — 손으로 수정하지 말 것.\n"
    "// 기반 facts: tools/state_base.py · 리서치: tools/aug_*.json · 순위는 50개 주 기준.\n"
    f"export const STATE_INFO = {body};\n",
    encoding="utf-8")
print("생성:", OUT)
